### ISSUE TITLE
Error:(23, 0) Could not find method compile() for arguments [project ':openCVLibrary320'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler. <a href="openFile:/Users/Lingzhi/Dev/Project/opencv-android-sample-master/build.gradle">Open File</a>

### ISSUE THREAD

**Issue by lzzhang75** [jlhonora/opencv-android-sample#2]
got this error. where is the issue in my project?

**Comment by jlhonora** [comment]
Hi, please enhance the problem description. A good guide on how to improve bug reports can be found [here](https://github.com/necolas/issue-guidelines/blob/master/CONTRIBUTING.md#bug-reports) . Feel free to reopen this issue if you can provide more information.
